# Generated by Django 2.2.16 on 2023-02-07 10:01

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230207_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[recipes.validators.hex_color_validaror], verbose_name='цвет'),
        ),
    ]
