# Generated by Django 2.2.16 on 2023-02-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230207_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resipes/images/', verbose_name='изображение'),
        ),
    ]
