# Generated by Django 2.2.16 on 2023-03-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230223_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='единицы измерения'),
        ),
    ]
