# Generated by Django 2.2.16 on 2023-04-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230402_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
